# 3분 파이토치

Shape, Size, Rank 및 Rank 변환에 대해서 공부.

In [21]:
import torch

x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [9]:
print("Size:", x.size())

print("Shape:",x.shape)

print("RANK:",x.ndimension())



Size: torch.Size([3, 3])


In [14]:
# 랭크 늘리기
x = torch.unsqueeze(x,0)
print("Size:", x.size())

print("Shape:",x.shape)

print("RANK:",x.ndimension())



Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
RANK: 3


In [15]:
x = torch.squeeze(x)
print(x)
print("Size:", x.size())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])


In [16]:
x=x.view(9)

print(x)
print("Size:", x.size())
print("Shape:",x.shape)
print("RANK:",x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
RANK: 1


In [20]:
try:
    x=x.view(2,4)
except Exception as e :
    print(e)

shape '[2, 4]' is invalid for input of size 9
