# Matrix

In [1]:
import tensorflow as tf

In [4]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]

y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
# 좀 다른 방식으로 선언 여기서 Matmul은 행렬곱을 도와주는 라이브러리
# 원래의 hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
hypothesis = tf.matmul(X, W) + b

# cost
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a Session
sess = tf.Session()

# Initializes global Variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost : ", cost_val, "\nPrediction: \n", hy_val)


0 Cost :  2106.9568 
Prediction: 
 [[107.56889]
 [137.59041]
 [130.99022]
 [146.43776]
 [103.86057]]
10 Cost :  5.2311363 
Prediction: 
 [[148.12834]
 [186.33151]
 [179.02007]
 [198.73956]
 [141.03691]]
20 Cost :  5.2041645 
Prediction: 
 [[148.25551]
 [186.47601]
 [179.16687]
 [198.89795]
 [141.14632]]
30 Cost :  5.196409 
Prediction: 
 [[148.26036]
 [186.47351]
 [179.16881]
 [198.89854]
 [141.14357]]
40 Cost :  5.1887484 
Prediction: 
 [[148.2648 ]
 [186.47055]
 [179.17029]
 [198.89868]
 [141.1405 ]]
50 Cost :  5.181098 
Prediction: 
 [[148.26926]
 [186.46764]
 [179.17178]
 [198.89882]
 [141.13745]]
60 Cost :  5.1734657 
Prediction: 
 [[148.27367]
 [186.46468]
 [179.17325]
 [198.89891]
 [141.13438]]
70 Cost :  5.1658964 
Prediction: 
 [[148.27808]
 [186.46173]
 [179.17473]
 [198.89905]
 [141.13135]]
80 Cost :  5.1583414 
Prediction: 
 [[148.28247]
 [186.45882]
 [179.1762 ]
 [198.89914]
 [141.1283 ]]
90 Cost :  5.150846 
Prediction: 
 [[148.28688]
 [186.45593]
 [179.17767]
 [198.89929

1020 Cost :  4.5683374 
Prediction: 
 [[148.65167]
 [186.21463]
 [179.30066]
 [198.90112]
 [140.8822 ]]
1030 Cost :  4.563149 
Prediction: 
 [[148.65515]
 [186.21233]
 [179.30183]
 [198.90105]
 [140.87996]]
1040 Cost :  4.557964 
Prediction: 
 [[148.65865]
 [186.21004]
 [179.30302]
 [198.90099]
 [140.87773]]
1050 Cost :  4.5528045 
Prediction: 
 [[148.66212]
 [186.20776]
 [179.30423]
 [198.90092]
 [140.87552]]
1060 Cost :  4.5476656 
Prediction: 
 [[148.66557]
 [186.20546]
 [179.30539]
 [198.90083]
 [140.87329]]
1070 Cost :  4.5425324 
Prediction: 
 [[148.66904]
 [186.20317]
 [179.30655]
 [198.90076]
 [140.87108]]
1080 Cost :  4.5374475 
Prediction: 
 [[148.67249]
 [186.20091]
 [179.30774]
 [198.9007 ]
 [140.86888]]
1090 Cost :  4.532344 
Prediction: 
 [[148.67595]
 [186.19867]
 [179.30893]
 [198.90063]
 [140.86671]]
1100 Cost :  4.5272923 
Prediction: 
 [[148.67935]
 [186.19638]
 [179.31009]
 [198.90053]
 [140.86449]]
1110 Cost :  4.5222387 
Prediction: 
 [[148.68279]
 [186.19414]
 [1

1970 Cost :  4.147516 
Prediction: 
 [[148.9488 ]
 [186.01974]
 [179.40291]
 [198.88809]
 [140.69987]]
1980 Cost :  4.1437554 
Prediction: 
 [[148.95158]
 [186.01791]
 [179.40387]
 [198.88788]
 [140.69824]]
1990 Cost :  4.139974 
Prediction: 
 [[148.95438]
 [186.01608]
 [179.40483]
 [198.88766]
 [140.69662]]
2000 Cost :  4.136244 
Prediction: 
 [[148.95714]
 [186.01428]
 [179.40578]
 [198.88745]
 [140.69502]]
