# Matrix

In [1]:
import tensorflow as tf

In [4]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')


# H(x1, x2, x3) = x1*w1 + x2*w2 + x3*w3
# 가설 예측 식
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [5]:

# cost / loss function
# 손실 추정 식
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Miniize. Need a very small learning rate for this data set
# 손실 최소화 식
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
# 손실 최소화
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
# 학습
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data,
                                            Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  83.67723 
Prediction
 [167.12079 185.10591 190.61523 204.56352 140.07138]
10 Cost:  40.12757 
Prediction
 [161.27275 178.12352 183.71117 197.04825 134.75456]
20 Cost:  39.91336 
Prediction
 [161.23053 178.11917 183.68271 197.02037 134.7602 ]
30 Cost:  39.700756 
Prediction
 [161.20596 178.13588 183.67508 197.01517 134.78189]
40 Cost:  39.48933 
Prediction
 [161.18152 178.15262 183.66756 197.01006 134.80357]
50 Cost:  39.27905 
Prediction
 [161.15712 178.1693  183.66005 197.00493 134.82518]
60 Cost:  39.069836 
Prediction
 [161.13281 178.18594 183.65253 196.99985 134.84676]
70 Cost:  38.861767 
Prediction
 [161.10854 178.20253 183.64507 196.99475 134.86826]
80 Cost:  38.654728 
Prediction
 [161.08434 178.2191  183.6376  196.9897  134.88971]
90 Cost:  38.448902 
Prediction
 [161.06021 178.23561 183.63017 196.98463 134.9111 ]
100 Cost:  38.24427 
Prediction
 [161.03615 178.25206 183.62276 196.9796  134.93242]
110 Cost:  38.040638 
Prediction
 [161.01213 178.26846 183.61536 196.97

970 Cost:  24.078888 
Prediction
 [159.17227 179.52698 183.04799 196.59207 136.58168]
980 Cost:  23.951784 
Prediction
 [159.15327 179.53995 183.04213 196.58817 136.59843]
990 Cost:  23.825361 
Prediction
 [159.13435 179.5529  183.03629 196.58427 136.61516]
1000 Cost:  23.699543 
Prediction
 [159.11545 179.56581 183.03046 196.58038 136.63184]
1010 Cost:  23.574398 
Prediction
 [159.09662 179.5787  183.02464 196.57649 136.64848]
1020 Cost:  23.449972 
Prediction
 [159.07784 179.59155 183.01884 196.57263 136.66507]
1030 Cost:  23.32624 
Prediction
 [159.0591  179.60435 183.01305 196.56876 136.6816 ]
1040 Cost:  23.20319 
Prediction
 [159.04042 179.61713 183.00728 196.56491 136.69809]
1050 Cost:  23.080803 
Prediction
 [159.02177 179.62985 183.00153 196.56107 136.71452]
1060 Cost:  22.95905 
Prediction
 [159.0032  179.64256 182.99579 196.55724 136.73094]
1070 Cost:  22.83788 
Prediction
 [158.98466 179.65526 182.99008 196.55344 136.74731]
1080 Cost:  22.717464 
Prediction
 [158.96619 179.